defaults:
  - base
  - _self_

model:
  _target_: mod_res_damage.models.terramind.TerramindBayeSiamNet
  num_classes: 4
  finetune: false
  output_layers: [1, 3, 5, 7, 11]

dataset:
  _target_: mod_res_damage.datasets.mbright.ModifiedBright
  root_path: ${hydra:runtime.cwd}/data/mbright
  input_size: 224
  cache_arrays: true
  augment: 8
  holdout: [ukraine-conflict]

trainer:
  _target_: mod_res_damage.trainers.Trainer
  n_epochs: 1
  ckpt_interval: 1
  eval_interval: 1
  log_interval: 1
  best_metric_key: 'mIoU'
  precision: fp32

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.0001
  betas: [0.9, 0.999]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 1024
  last_epoch: -1

criterion:
  _target_: torch.nn.CrossEntropyLoss
  reduction: 'none'

activation:
  _target_: torch.nn.Softmax
  dim: 1

evaluator:
  _target_: mod_res_damage.evaluators.SegEvaluator
  inference_mode: random
  inference_batch: 20
  num_monte_carlo: 16
  save_probs: true
  
use_wandb: false
num_workers: 0
use_final_ckpt: true
find_unused_parameters: false
pin_memory: true
persistent_workers: false

train_batch_size: 20
test_batch_size: 1

