defaults:
  - base
  - _self_

model:
  _target_: mod_res_damage.models.unet.UNet3D
  n_channels: 2
  n_predictands: 1
  num_frames: 2
  bilinear: false
  kernel_size: [1,3,3]
  stride: 1
  padding: [0,1,1]
  embed: false

dataset:
  _target_: mod_res_damage.datasets.mbright.ModifiedBright
  root_path: ${hydra:runtime.cwd}/data/mbright_gee
  input_size: 224
  cache_arrays: true
  augment: 64
  holdout: ???
  average_time: true
  exclude: ["ukraine-conflict_group-1", "beirut-explosion_group-0"]

trainer:
  _target_: mod_res_damage.trainer.Trainer
  n_epochs: 256
  ckpt_interval: 32
  eval_interval: 16
  log_interval: 1
  best_metric_key: 'RMSE'
  precision: fp32

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.00001
  weight_decay: 0.00001
  betas: [0.9, 0.999]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 8092
  last_epoch: -1

criterion:
  _target_: torch.nn.HuberLoss
  reduction: 'none'

activation:
  _target_: torch.nn.Sigmoid

evaluator:
  _target_: mod_res_damage.evaluator.Evaluator
  inference_mode: random
  inference_batch: 64
  num_monte_carlo: 256
  save_output: true
  task: regression
  
use_wandb: true
num_workers: 0
use_final_ckpt: true
find_unused_parameters: false
pin_memory: false
persistent_workers: false

train_batch_size: 8
test_batch_size: 1

